### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by nathanrsxtn** [eschutz/atom-wpilib#1]
[Enter steps to reproduce:]

1. Clicked install

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Education
**Thrown From**: [atom-wpilib](https://github.com/eschutz/atom-wpilib) package 0.1.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:28

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:501:7)
    at /packages/atom-wpilib/lib/atom-wpilib.js:76:25)
    at /packages/atom-wpilib/lib/atom-wpilib.js:274:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:641362)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3029314)
    at Package.activateConfig (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3018673)
    at PackageManager.t.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:892672)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2932592)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2922872)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2922695)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2930825
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2932843
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:901852)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899261
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -1:30.5.0 core:copy (input.hidden-input)
  2x -1:30.2.0 core:paste (input.hidden-input)
  2x -1:27.3.0 core:delete (input.hidden-input)
     -1:02.2.0 core:save (input.hidden-input)
     -0:42.5.0 diagnostics:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-wpilib 0.1.1 
busy-signal 2.0.0 
file-icons 2.1.27 
ide-java 0.8.3 
```

**Comment by eschutz** [comment]
I've tracked down the issue to a usage of process.env.HOME, which doesn't work on windows. I'm away from my computer right now but I should be able to fix it in a few hours. Thanks for submitting this! :)

I haven't been able to test on a windows environment, so once you can install it I'll try and get to any other issues asap.

**Comment by eschutz** [comment]
@nathanrsxtn I've published a patch for the issue, please let me know if it helps or you run into any other problems.

**Comment by nathanrsxtn** [comment]
That solved the problem and the package is installed, but it doesn't do anything when I click on the menu items. I think it has something to do with my C:\Users\Spencer\wpilib\user\java\lib folder being empty

**Comment by eschutz** [comment]
That's for gradlerio config, is gradlerio installed?
Could you try wpilib:generate-project, and tell me what happens?

**Comment by nathanrsxtn** [comment]
I think GradleRIO is installed. I ran the installer from [https://github.com/wpilibsuite/allwpilib/releases](https://github.com/wpilibsuite/allwpilib/releases).
Running wpilib:generate-project gives an error and makes some files in the project directory.
![wpilib generate error](https://user-images.githubusercontent.com/37890449/50950233-90cbb600-1466-11e9-9c36-7ebf0cc02774.png)
![wpilib generate error 2](https://user-images.githubusercontent.com/37890449/50950477-4bf44f00-1467-11e9-96d8-062b2dc2fcaa.png)

**Comment by eschutz** [comment]
Try opening a command prompt and executing 'gradle', if the same message as in that error appears it means gradle is likely not installed (gradle *should* be installed since you used the installer). It might be worth re-running the installer to ensure gradle is installed.

**Comment by nathanrsxtn** [comment]
Sorry for the long response, I was at school. Gradle didn't work, I will try to reinstall it.
![untitled](https://user-images.githubusercontent.com/37890449/51005648-f5d1eb00-14fc-11e9-8e49-3fd0b6b4ebe8.png)

**Comment by nathanrsxtn** [comment]
Ok, I ran the installer here: [https://github.com/wpilibsuite/allwpilib/releases](https://github.com/wpilibsuite/allwpilib/releases) and it successfully installed, but the gradle command still doesn't work.
I downloaded this: [https://github.com/wpilibsuite/GradleRIO/releases](https://github.com/wpilibsuite/GradleRIO/releases) and ran the bat file and got this error message:
![untitled](https://user-images.githubusercontent.com/37890449/51006162-36326880-14ff-11e9-9a58-93c8de82c8e4.png)

**Comment by nathanrsxtn** [comment]
After reading the error message, I can confirm the frcHome folder mentioned `C:\Users\Public\frc2019\maven\edu\wpi\first\GradleRIO` exists and has a `maven-metadata.xml` file and a folder named `2019.1.1` with GradleRIO jars in it. I do not have a `.m2` folder, but I have a `.p2` folder, not sure if that is related because it has eclipse files in it.

**Comment by eschutz** [comment]
I'm getting the same issue running `gradlew`, and the GradleRIO version specified in `build.gradle` is `4242.1.1-ci` which makes me think a continuous integration (CI) build may have been included in the release. Changing the version to `2019.1.1` fixed the issue for me, and this seems to be the latest version in accordance with https://plugins.gradle.org/plugin/edu.wpi.first.GradleRIO. Could you see if this works for you?

**Comment by eschutz** [comment]
I'm closing this issue since we moved onto a different one, see issue #3 to continue the discussion.
