### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by nathanrsxtn** [eschutz/atom-wpilib#4]
Having another issue, not sure if it is related:
1. Ran build robot code from packages menu.
2. Running it again doesn't trigger the error but still doesn't build.

`C:\Users\62820\AppData\Local\atom\app-1.34.0\resources\app` only has an `apm` folder.
Builds in visual studio word fine.

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Education
**Thrown From**: [atom-wpilib](https://github.com/eschutz/atom-wpilib) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At C:\Users\62820\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.t.exports.CommandLogger.logCommand (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:877750)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:877072
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:349649)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:348492)
    at refreshBuild (/packages/atom-wpilib/lib/atom-wpilib.js:125:30)
    at HTMLElement.wpilibBuild (/packages/atom-wpilib/lib/atom-wpilib.js:134:29)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:671034)
    at EventEmitter.t (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:678418)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:03.9.0 wpilib:build (atom-pane.pane)
```

### Non-Core Packages

```
atom-wpilib 0.1.2 
build 0.70.0 
busy-signal 2.0.0 
```

**Comment by eschutz** [comment]
If you select a text editor before executing it again, does it work? The node where the command is dispatched uses the active text editor, I think the build window takes focus away from it so there is no active text editor.
I'm not at my computer currently but I will be soon where I can fix it. Thanks for submitting another report.

**Comment by eschutz** [comment]
Published [v0.1.3](https://github.com/eschutz/atom-wpilib/releases/tag/v0.1.3)
Please let me know if the issue is fixed @nathanrsxtn.

**Comment by nathanrsxtn** [comment]
I've been having issues with my home computer so I will not be able to test this fix until I'm back at school. I'll let you know if it works when I can.

**Comment by nathanrsxtn** [comment]
Sorry for the long response, I updated and it solved the problem.
Thanks @eschutz!
